# Generated by Django 4.2 on 2024-04-23 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('nomImagen', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='RelacionUP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=25)),
                ('garantia', models.CharField(max_length=25)),
                ('numero_serie', models.CharField(max_length=35)),
                ('imei', models.CharField(max_length=45)),
                ('modelo', models.CharField(max_length=35)),
                ('fk_productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.productos')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
