version: '3.8'

services:
  web:
    build: .
    container_name: wattcontrol_web
    command: >
     sh -c "/wait-for-it.sh wattcontrol_db:3306 -- python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=WattControl.settings

  db:
    image: mysql:8.0
    container_name: wattcontrol_db
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:


  