version: '3.8'

services:
  web:
    build: .
    container_name: wattcontrol_web
    command: >
      sh -c "/wait-for-it.sh wattcontrol_db:3306 -t 30 -- python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    expose:
      - "8000"  # Solo accesible internamente
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=WattControl.settings
    networks:
      - internal_network
      - external_network  # Accesible desde NGINX

  db:
    image: mysql:8.0
    container_name: wattcontrol_db
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3309:3306"  # Solo para pruebas locales, elimina en producción
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - internal_network  # Solo accesible internamente

  nginx:
    image: nginx:latest
    container_name: wattcontrol_nginx
    ports:
      - "443:443"  # HTTPS
      - "80:80"    # HTTP (opcional, redirige a HTTPS)
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/ssl/certs:ro  # Certificados SSL
      - ./certs:/etc/ssl/private:ro
    depends_on:
      - web
    networks:
      - external_network  # Accesible externamente

  backup:
    image: mysql:8.0
    container_name: wattcontrol_backup
    command: >
      sh -c "while true; do
      mysqldump -h db -u root -p${MYSQL_ROOT_PASSWORD} ${MYSQL_DATABASE} > /backups/db_backup_$(date +\%F_%T).sql;
      sleep 86400;
      done"
    volumes:
      - ./backups:/backups  # Carpeta local para almacenar los backups
    depends_on:
      - db
    networks:
      - internal_network


  volume_backup:
    image: alpine:latest
    container_name: wattcontrol_volume_backup
    command: >
      sh -c "while true; do
      tar -czvf /backups/db_data_backup_$(date +\%F_%T).tar.gz /data;
      sleep 86400;
      done"
    volumes:
      - db_data:/data  # Monta el volumen de la base de datos
      - ./backups:/backups  # Carpeta local para almacenar los backups
    depends_on:
      - db
    networks:
      - internal_network

volumes:
  db_data:

networks:
  internal_network:
    driver: bridge
  external_network:
    driver: bridge