version: '3.8'

services:
  web:
    build: .
    container_name: wattcontrol_web
    command: >
     sh -c "/wait-for-it.sh wattcontrol_db:3306 -- python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    expose:
      - "8000"  # Solo accesible internamente
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=WattControl.settings
    networks:
      - internal_network
      - external_network  # Accesible desde NGINX

  db:
    image: mysql:8.0
    container_name: wattcontrol_db
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3309:3306"  # Solo para pruebas locales, elimina en producción
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - internal_network  # Solo accesible internamente

  nginx:
    image: nginx:latest
    container_name: wattcontrol_nginx
    ports:
      - "443:443"  # HTTPS
      - "80:80"    # HTTP (opcional, redirige a HTTPS)
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/ssl/certs:ro  # Certificados SSL
      - ./certs:/etc/ssl/private:ro
    depends_on:
      - web
    networks:
      - external_network  # Accesible externamente

volumes:
  db_data:

networks:
  internal_network:
    driver: bridge
  external_network:
    driver: bridge